### ISSUE TITLE
Missing Typescript Definitions

### ISSUE THREAD

**Issue by Aryaman73** [teslamotors/informed#354]
Hey! It seems like the `index.d.ts` file is out of date (a comment in the file mentions Informed v2.0.0). Notably, this means that the `Multistep` component [(here)](https://github.com/joepuzzo/informed/blob/master/src/components/Multistep.js) is seemingly unusable in a TS project: 

![image](https://user-images.githubusercontent.com/53343807/126197296-13672af3-ec92-42c1-a0e9-a8e6fc25d277.png)

The only solution for this that I could find is to disable TS (and esLint) in the file, which isn't ideal. 

I know that this is also the case with the `Relevant` component, and that the maintainer of this project doesn't use Typescript too much [(link)](https://github.com/joepuzzo/informed/issues/302), but I was wondering if there was any progress made on the TS definitions since then?

----

As a side note, there seems to be a mistake in the example in the documentation [here](https://joepuzzo.github.io/informed/?path=/story/multistep-forms--dynamic-multistep) in the code example at the bottom of the page. It's missing a closing `</div>`:
![image](https://user-images.githubusercontent.com/53343807/126197859-52e87565-48e2-4d09-82ae-6381debeec68.png)

**Comment by Bezmehrabi** [comment]
Hi :), I have the same problem too. I'm working on it and will make a PR for it.

**Comment by Aryaman73** [comment]
@Bezmehrabi awesome! 🥳 I'd love to have a look/test it out once you're done.

**Comment by joepuzzo** [comment]
Im going to redo them soon. I just need to get help from a TS person lol

**Comment by Bezmehrabi** [comment]
hello, I've been busy unfortunately but I did some work because we needed the type definition to be fixed for our own needs. :)
the current type definition has a lot of problems. for example, field name type is a lot more complex than just `[key: k in keyof V]` because of nested values.

[react-hook-form](https://github.com/react-hook-form/react-hook-form) has some great type utils for this kind of types.
and I suggest using them :).

**Comment by Bezmehrabi** [comment]
it's been a long time...but I finally did it  xD

**Comment by joepuzzo** [comment]
Those types are too complex. I will not merge them. ( I will work on adding missing types now that V4 is out ) But I WONT make them complex
