### ISSUE TITLE
relevant is working only for formState changes?

### ISSUE THREAD

**Issue by SoloDev45** [teslamotors/informed#372]
In my 4.0.13 version of informed relevant is working fine with the formState. But when I tried to give a state value to relevant it isn't working as expected. The relevance of MultieStep.Step is working fine only for the change in the formState but not for the change in the component state.

**Comment by joepuzzo** [comment]
Please provide code sandbox or code snippets with these issues. Its hard to determine the issue from sentences. ( pictures worth a thousand words ) 😁

**Comment by joepuzzo** [comment]
Sandboxes are always better!

**Comment by SoloDev45** [comment]
> Sandboxes are always better!

Here is my code sandbox link, Here I am trying to render the second step relevantly based on a state variable **isLoggedIn**. But even though the state variable is getting changed the relevant is working with the initial state variable only. 

How can I resolve this?

https://codesandbox.io/s/multie-step-practice-6kfhe?file=/src/App.js

**Comment by joepuzzo** [comment]
Ok I have added fix to informed ( forgot to allow you to pass `relevanceDeps` ) to multisteps

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/multie-step-practice-forked-vrcl7?file=/src/App.js

Updated sandbox ( I added a toggle button for logged in on the third step )

**Comment by SoloDev45** [comment]
> 
Yeah the problem is if the **isLoggedIn** value is **true** then if we try to go the previous step by calling the **previous** function it should go to **firstStep** instead of the second step because we are giving isLogged value in relevanceDeps. 

But the codesandbox that you have provided is not working in that way. The second step is being rendered irrespective of the isLogggedIn value

**Comment by joepuzzo** [comment]
If you try to set isLogged in to false at the same time you call previous then it will never work because the state change happens after the the form evaluates relevance, however if you dont do it at that point then it will work fine so please try again with updated code.

**Comment by joepuzzo** [comment]
Ok this is simple function closure issue https://codesandbox.io/s/multie-step-practice-forked-c09m6?file=/src/App.js 

The problem is that the loggedIn variable is outdated in the `relevant` function that was originally passed to the step. I can maybe look into updating that function reference somehow but need to think on it. 

Please use the linked workaround for now by using a ref to that variable.

**Comment by SoloDev45** [comment]
Ok! for now, I will use it by using a ref to that variable.

Thanks and Appreciation for the response Dude  :clap: :clap:
