### ISSUE TITLE
previous is not working in an expected manner

### ISSUE THREAD

**Issue by SoloDev45** [teslamotors/informed#374]
**Describe the bug**
In the below code sandbox link I have given the previous as "firstStep" at the third step but when I call the previous function it is going to secondStep instead of firstStep. 

Does the feature giving next and previous steps at MultieStep.Step has been removed?

**To Reproduce**

https://codesandbox.io/s/multie-step-practice-forked-vrcl7?file=/src/App.js

![Screenshot from 2021-12-18 17-16-21](https://user-images.githubusercontent.com/96132276/146639803-5cdfc288-0561-4333-ae82-185af95ca583.png)

**Comment by joepuzzo** [comment]
Yes it does it for you now
