### ISSUE TITLE
getApi

### ISSUE THREAD

**Issue by wahlstedt** [teslamotors/informed#377]
The `getApi` form prop also seems to have disappeared? Nothing mentioned about it in the changelog. 
I used it to set some form input fields when the form is submitted or when certain keys are pressed during input. The currently listed methods to get access to the api doesn't seem to work from outside the form.

**Comment by joepuzzo** [comment]
Use formApiRef now . Same thing

**Comment by wahlstedt** [comment]
Thanks, that worked. Could be useful to add to the migration guide for v4.

**Comment by joepuzzo** [comment]
There is its in the changelog:) i may be missing some things but its there! Go give it a read

**Comment by wahlstedt** [comment]
I did a search of the entire repo for `getApi` and only got one mention of it (from the June 12, 2018 update).  🤔

**Comment by joepuzzo** [comment]
Yup then i forgot to add that to migration. My bad. I will add

**Comment by wahlstedt** [comment]
No worries, we figured it out pretty quickly. :) 

While you're at it, can you add info about the `Text` input ( #376)? That's another thing that tripped me up while migrating.

**Comment by joepuzzo** [comment]
Sure will do!
