### ISSUE TITLE
Could not resolve "react-native-config"

### ISSUE THREAD

**Issue by denno020** [teslamotors/informed#394]
**Describe the bug**
Just updated to the latest version of Informed and it's now breaking my build

**To Reproduce**

![image](https://user-images.githubusercontent.com/2059313/154627647-3fe800e2-5c5d-454c-a9a0-b7c46c59fd1c.png)

**Comment by joepuzzo** [comment]
Will fix thanks for letting us know

**Comment by denno020** [comment]
Seems to have done the trick! Thanks @joepuzzo
