### ISSUE TITLE
Missing SchemaFields, Debug types

### ISSUE THREAD

**Issue by shelbyspeegle** [teslamotors/informed#402]
**Describe the bug**
`SchemaFields` and `Debug` type are missing from the typings in the `informed` module.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7694692/165138122-b40fd23a-5461-4d2c-865e-abeaedf2b57b.png">

**To Reproduce**

- Open [this CodeSandbox link](https://codesandbox.io/s/objective-tu-ce9vzy?file=/src/App.tsx) which is based on [this storybook story](https://teslamotors.github.io/informed/?path=/story/schema--schema).
- Open `App.tsx` and you will see two typescript errors, one for `SchemaFields` missing, and another for `Debug`.

I plan to write up a quick PR for this shortly to address these two types specifically.

**Comment by joepuzzo** [comment]
Yup I will get these added thanks !

**Comment by joepuzzo** [comment]
Oh or make a PR that works too!!
