### ISSUE TITLE
Providing Form with new schema with updated property appears to have no effect in specific case.

### ISSUE THREAD

**Issue by shelbyspeegle** [teslamotors/informed#404]
**Describe the bug**
I am attempting to have a schema property start as `<input type=text />` and change to `<select />` after an async call is completed. I am essentially looking to achieve this effect in the gif below:

![informed-schema-update](https://user-images.githubusercontent.com/7694692/168893837-cb6815e7-9530-4972-bb4b-74d7ee075681.gif)

- ❌  Providing new `schema` property to `<Form />` component seems to have no effect if changing a property from `{ type: 'string' }` to `{ type: 'string', oneOf: [] }` (`<input type=text />` to `<select />`).
- ✅  If the property name changes between schema updates the UI will update.
- ✅  If the Form is unmounted between the schema updates the form UI will update.

**To Reproduce**
Please see [this CodeSandbox](https://codesandbox.io/s/modest-meitner-k87jqr?file=/src/App.js) for code that reproduces the behavior I described. In the CodeSandbox I am switching between two schemas every second, but only the `<input type="text" />` is rendered. See the console for when these updates are occurring since it can kind of look like just a static page.

I have achieved the effect in the gif above by changing the property name from `model` to `modelz` (see second ✅  above).

Should this work this way or is this functioning as expected?

**Comment by joepuzzo** [comment]
OK so this is interesting. We only parse the schema once at the beginning. We do this because we don't want to compare a large schema nor do we want to assume the user is passing in the same object reference.

**Comment by joepuzzo** [comment]
There are ways to conditionally change the input props but this is interesting as you are doing more than that.. you are changing the actual input type! Let me think on this one 🤔

**Comment by joepuzzo** [comment]
Technically a new schema is a new form. So you would lose all your state. IS your goal to keep the state and just change input type ?

**Comment by shelbyspeegle** [comment]
Ahh ok. If that is true then I may change my strategy to just wait to build the form once all dependencies are resolved.

Yes, ideally we would be able to keep form state as inputs resolve to ones that contain list of options. I was picturing something like having initial inputs as disabled selects with a spinner on them showing that list is loading and then when finally loaded the user can actually interact with them. I can't find an example but know I have seen that somewhere.

I will go with waiting for all options to resolve before building the form for now, but will be curious to see if something like this ever gets rolled out!

**Comment by shelbyspeegle** [comment]
Feel free to close - we can work around unless you see this as a feature you want to work to add 👍

**Comment by joepuzzo** [comment]
Ok also if your curious for conditional schema stuff there may be stuff you need 
here: https://teslamotors.github.io/informed/?path=/story/conditionals--conditional-props-schema
