### ISSUE TITLE
onSubmit type definition

### ISSUE THREAD

**Issue by wahlstedt** [teslamotors/informed#411]
https://github.com/teslamotors/informed/blob/0ea7dbcb1d1e8ef9ceffe24324ebd5f970fba49d/index.d.ts#L130

Shouldn't onSubmit have the same type as most of the others:  `(formState: FormState) => void;`

The docs says it includes the formState too.

**Comment by joepuzzo** [comment]
Yes I will fix this!

**Comment by joepuzzo** [comment]
Fixed in latest `4.19.3`
