### ISSUE TITLE
onChange, how to get access to all field event properties?

### ISSUE THREAD

**Issue by akshare** [teslamotors/informed#416]
I'm using custom fields following the example here: 

https://teslamotors.github.io/informed/?path=/story/custominputs--creating-custom-inputs

On the implementation side, when calling onChange for the input fields, I have access to informed event like so:

```
{
  value: "value from input field"
  maskedValue: "n"
  modified: true
  touched: false
  error: undefined
  data: undefined
  pristine: false
  dirty: true
  valid: true
  invalid: false
  showError: false
  validating: false
  gathering: false
  focused: true
}
```

Is it also possible to access all field event properties via e.target.name, e.target.checked etc?

https://codesandbox.io/s/silly-https-ey1kyx?file=/src/App.js

**Comment by akshare** [comment]
I've tried implementations of this as well, but the event properties are limited to the output above.

https://teslamotors.github.io/informed/?path=/story/hooks--usefield

**Comment by akshare** [comment]
I got it to work, but I had to access onChange using props.onChange.

```
const { onChange, onBlur, ...rest } = userProps;

onChange={(e) => {
        setValue(e.target.value);

        if (props.onChange) {
          props.onChange(e);
        }
}}
```

https://codesandbox.io/s/new-thunder-11z9mf?file=/src/App.js

**Comment by joepuzzo** [comment]
Wait the second parameter of all the onChanges is the native e event. So just use that

**Comment by joepuzzo** [comment]
See here https://github.com/teslamotors/informed/blob/master/src/FormController.js#L394

**Comment by akshare** [comment]
Ah, I get it now.

Thanks for all your work and your help on this!

```
// on the custom element

onChange={e => {
  setValue(e.target.value, e);
}}

//on the implementation
  function handleInput(informedEvent, nativeEvent) {
    console.log(informedEvent);
    console.log(nativeEvent);
  }
```
