### ISSUE TITLE
Console log displayed when input has mask

### ISSUE THREAD

**Issue by mihaicracan** [teslamotors/informed#429]
Hi guys,

You are doing an amazing work!

Just wanted to say there is a console.log left inside src/FormController.js which was added for testing on this commit (line 339):
https://github.com/teslamotors/informed/commit/d3af9f2bb3eeff8acd3b1310058accfb39e6b051

It would be great if we remove this one as there are lots of console logs now inside our application. 😅

Thank you!

**Comment by joepuzzo** [comment]
Oh wow thanks! Will remove now and deploy a new version

**Comment by joepuzzo** [comment]
Fixed in the latest version
