### ISSUE TITLE
onSubmit - setError is not a function

### ISSUE THREAD

**Issue by cherring07** [teslamotors/informed#432]
Perhaps undocumented (sorry if I have missed it)

When using the useFormAPI hook with setError within onSubmitI get the following error. 

`formApi.setError is not a function`

```
const Test= () => {
  const formApi = useFormApi();

  const onSubmit = () => {
    formApi.setError('example', 'error!');
  };
  
  render (  
     <Form onSubmit={onSubmit}>
      <Input name="example" label="Example" />
      <button type="submit">Submit</button>)
     </Form>
     );
}
```

**Comment by joepuzzo** [comment]
You are outside the context of the form. 

1. I would highly reccomend NOT setting errors directly as there is a lifecylce for this
2. If you do need the formApi outside of the context of a `<Form` you need to use `<Form formApiRef={someRef}`

Then you can do `formApiRef.current.setValue('example', 'Foo')` as an example
