### ISSUE TITLE
TextArea - attribute

### ISSUE THREAD

**Issue by tKanashiro** [teslamotors/informed#438]
**Describe the bug**
I'm using informed in Typecript project, and it's complaining the type for `rows` doesn't exist in  `<TextArea />` props.
All props listed inside `interface InputHTMLAttributes` is fine, but it's not the same for the ones listed inside `interface HTMLTextAreaElement`.
Please see the link and image below.

**To Reproduce**
https://codesandbox.io/s/crimson-butterfly-wkzvlx?file=/src/App.tsx

![2023-01-11_13-18](https://user-images.githubusercontent.com/94497782/211706442-5ae4119c-752b-4fd4-92ea-9c8e5ddd8209.png)

**Comment by abelmark** [comment]
I'm trying to push a fix for this, but am getting permission denied... @joepuzzo 👀

**Comment by joepuzzo** [comment]
Make a PR for it

**Comment by joepuzzo** [comment]
Remember this is an Open Source Package not in teslas internal git. You need to fork it like any other user and then make PR from your fork
