### ISSUE TITLE
Zod support

### ISSUE THREAD

**Issue by quinnvaughn** [teslamotors/informed#445]
Any plans to explicitly support Zod? Not sure if there are workarounds and I just missed that my first time through, but looks like it only explicitly supports yup so far?

**Comment by joepuzzo** [comment]
Hmm not sure if I want to keep adding more validation stuff into the lib rather than potentially writing your own wrapper. Let me think on this. For now you should be able to use `validateFields` on the `<Form>` and `validate` on fields to achieve this same thing with a util function.
