### ISSUE TITLE
upon  using npm run dev command its throwing an error

### ISSUE THREAD

**Issue by samr874** [teslamotors/informed#470]
I want to run the application  by using **npm run dev**
I am getting this error how to resolve this issue by using which commands
`
![image](https://github.com/teslamotors/informed/assets/60845180/a7376bcc-a091-44ad-a4d2-fca530eb9fd7)
`

**Comment by joepuzzo** [comment]
try npm run start

**Comment by samr874** [comment]
> try npm run start

but its saying that D:/informed/dist/esm this file is missing 
![image](https://github.com/teslamotors/informed/assets/60845180/684f4510-4c4f-4970-ba15-6221720a4dec)
what to do is it the same case from your end??

**Comment by joepuzzo** [comment]
ahhh can you run npm run build first

**Comment by joepuzzo** [comment]
I think I need to update README

```
npm run build

npm run start 
```

Build will build the source code

Start will start a dev server for the docs

**Comment by joepuzzo** [comment]
Note, you need to re build if you make code changes to src for them to take affect in the local docs

**Comment by samr874** [comment]
@joepuzzo Thank you will try to update it will follow the solutions as follows

**Comment by samr874** [comment]
@joepuzzo actually the error http://localhost:5173/informed/dist/esm this url is throwing response as 404 not found

**Comment by joepuzzo** [comment]
1. Are you running at least node version 18 
2. Did you make sure to npm install everything
3. You ran npm run build
4. You ran npm start ? 

I just did all the following and see no issues

**Comment by samr874** [comment]
just try to inspect the application @joepuzzo this http://localhost:5173/informed/dist/esm URL is throwing the problem

**Comment by joepuzzo** [comment]
That tells me you did not have a successful build after `npm run build`

**Comment by joepuzzo** [comment]
<img width="796" alt="Screenshot 2024-03-11 at 12 17 40 PM" src="https://github.com/teslamotors/informed/assets/9516899/5f8d885f-2328-4f77-b68c-237d9e9c1911">

**Comment by joepuzzo** [comment]
This is what a successful build looks like

**Comment by samr874** [comment]
so I have to pull from master branch as per your terminal

**Comment by samr874** [comment]
what is your solution to this

**Comment by samr874** [comment]
> 1. Are you running at least node version 18
> 2. Did you make sure to npm install everything
> 3. You ran npm run build
> 4. You ran npm start ?
> 
> I just did all the following and see no issues

yes I did everything but still the same issue

**Comment by joepuzzo** [comment]
There is no problem to fix.. there is simply following the layed out. 

1. Are you running at least node version 18
2. Did you make sure to npm install everything
3. You ran npm run build
4. You ran npm start ?

your error indicates that you never successfully build the code with npm run build. You need to get that to happen.

**Comment by joepuzzo** [comment]
let me ask you this... do you have a dist directory that was created after you ran npm run build ? 

And in that directory do you have an esm directory ?

**Comment by samr874** [comment]
no there is no dist directory

**Comment by joepuzzo** [comment]
Then the build never succeeded. Are you on a mac or windows machine?

**Comment by samr874** [comment]
I am on windows
what to do now

**Comment by joepuzzo** [comment]
run a terminal that has bash. you can google how to do this. The problem is all development done on this project is done on mac or linux and the build command relys on a few unix commands so thats prob why its failing. 


Just google "how to run bash terminal on windows"

**Comment by samr874** [comment]
are you sure will it work but what difference does it make of os

**Comment by joepuzzo** [comment]
Ha literally its just this https://github.com/teslamotors/informed/blob/master/package.json#L23

The fact that it runs a `rm -rf dist && rollup` that is unix command / syntax to run stuff.

**Comment by joepuzzo** [comment]
so yes if you run in a terminal that supports unix/linux commands it should work fine

**Comment by joepuzzo** [comment]
Why are you trying to run this locally in the first place may I ask ? Are you looking to contribute? Learn? Test?

**Comment by samr874** [comment]
@joepuzzo thank you so much now it's working

so the contributors working on windows os.
use this as script "build": "rimraf dist && rollup --config && npm run fix:cjs"
